# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faeba349039cc7479ff512d20aa642f89f42caeb932afafe43c847e8fa5fb64941937f950978d695290c86fe2ec70005ea117040205b06045b8cb7f30edb1bdb

test:
  secret_key_base: 6c398cf2027b1bb68dfe9bd7afabe805e5340f53b2c302483fdb2c7d73c6a3b6fe7da302ab1cc9dcce7a473953dca21d75a2e4797a0a86625ad6743427319693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
